# Generated by Django 3.2.6 on 2022-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editimage', models.ImageField(default='', upload_to='imagecrop/Editimage')),
            ],
        ),
    ]
