# Generated by Django 3.2.6 on 2022-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecrop', '0002_alter_editpicture_editimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpicture',
            name='editimage',
            field=models.ImageField(default='', upload_to='imagecrop/Editimage'),
        ),
    ]
