# Generated by Django 3.2.6 on 2022-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editimage', models.ImageField(default='', upload_to='imageresize/Editimage')),
            ],
        ),
        migrations.CreateModel(
            name='Editzipfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editzipfile', models.FileField(storage='imageresize/zipfiles', upload_to='')),
            ],
        ),
    ]
